---
title: "Application Exercise 15 - Communicate your results"
format: revealjs
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  warning: false
---

```{r}
library(tidyverse)
```


```{r}
waste_data <- read_csv("data/raw_data/msw-generation-and-composition-by-income.csv")
```

```{r}
income_cat_levels <- c("low income", "lower-middle income", "upper-middle income", "high income")

waste_generation_tidy <- waste_data %>% 
  drop_na(msw_capita_kg_year) %>% 
  mutate(income_cat = factor(income_cat, levels = income_cat_levels)) 

```

```{r}

waste_generation_tbl <- waste_generation_tidy %>% 
  group_by(income_cat) %>% 
  summarise(
    count = n(),
    min = min(msw_capita_kg_year),
    mean = mean(msw_capita_kg_year),
    sd = sd(msw_capita_kg_year),
    max = max(msw_capita_kg_year)
  )

```


# Introduction

## What a Waste!

# Results & Discussion

## Waste generation 

- See @tbl-waste-generation

```{r}
#| label: tbl-waste-generation
#| tbl-cap: "Waste generation by income category."

waste_generation_tbl %>% 
  rename(`income category` = income_cat) %>% 
  knitr::kable(digits = 0)

```

## Waste generation 

- See @fig-waste-generation

```{r}
#| label: fig-waste-generation
#| fig-cap: "Waste generation by income category."

ggplot(data = waste_generation_tidy,
       mapping = aes(x = income_cat, 
                     y = msw_capita_kg_year,
                     color = income_cat)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.2) +
  scale_y_continuous(breaks = seq(0, 1600, 200)) +
  scale_color_brewer(type = "qual", palette = "Paired") +
  labs(title = "Waste generation by income category",
       x = NULL,
       y = "MSW generation per capita [kg/year]") +
  theme_minimal(base_size = 14) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position = "none") 

```